/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.br.VIEW;

import com.br.DAO.MembroDAO;
import com.br.DTO.MembroDTO;
import java.awt.Color;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.Period;
import java.time.ZoneId;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author lukas
 */
public class FrmCadastrarMembroVIEW extends javax.swing.JFrame {

    /**
     * Creates new form FrmAdicionarMembro
     *
     * @throws java.text.ParseException
     */
    public FrmCadastrarMembroVIEW() throws ParseException {
        getContentPane().setBackground(Color.DARK_GRAY);
        initComponents();
        ListarMembros();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dateChooserDialog1 = new datechooser.beans.DateChooserDialog();
        dateChooserDialog2 = new datechooser.beans.DateChooserDialog();
        dateChooserDialog3 = new datechooser.beans.DateChooserDialog();
        dateChooserDialog4 = new datechooser.beans.DateChooserDialog();
        btnExcluirMembro = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        txtNomeMae = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        txtCPF = new javax.swing.JFormattedTextField();
        dateNascimento = new datechooser.beans.DateChooserCombo();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtNomePai = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        cbxEstadoCivil = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        txtNatural = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        cbxUF = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        txtNacionalidade = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txtEndereco = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txtNum = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        txtBairro = new javax.swing.JTextField();
        txtCEP = new javax.swing.JFormattedTextField();
        jLabel17 = new javax.swing.JLabel();
        txtCelular = new javax.swing.JFormattedTextField();
        jLabel7 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        txtConjugue = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        btnCadastrarMembro = new javax.swing.JButton();
        btnAlterarRegistro = new javax.swing.JButton();
        btnCarregarCampos = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaMembro = new javax.swing.JTable();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnExcluirMembro.setBackground(new java.awt.Color(204, 0, 51));
        btnExcluirMembro.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnExcluirMembro.setForeground(new java.awt.Color(255, 255, 255));
        btnExcluirMembro.setText("<html><p sytle text_align:center;>EXCLUIR<br>MEMBRO</p></html>");
        btnExcluirMembro.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnExcluirMembro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirMembroActionPerformed(evt);
            }
        });

        jTabbedPane1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTabbedPane1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jTabbedPane1.setPreferredSize(new java.awt.Dimension(840, 500));

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 51), 5));

        txtNomeMae.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Data de Nascimento");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Nome");

        txtNome.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        try {
            txtCPF.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtCPF.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        dateNascimento.setCalendarPreferredSize(new java.awt.Dimension(320, 220));
        dateNascimento.setFormat(2);
        dateNascimento.setFieldFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 14));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("CPF");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Nome do Pai");

        txtNomePai.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtNomePai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomePaiActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Nome da Mãe");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Registro");

        txtId.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtId.setEnabled(false);

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Estado Civil");

        cbxEstadoCivil.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        cbxEstadoCivil.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Solteiro(a)", "Casado(a)", "Divorciado(a)", "Viúvo(a)" }));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Natural");

        txtNatural.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("UF");

        cbxUF.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        cbxUF.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "RJ\t", "AC\t", "AL", "AP\t", "AM\t", "BA\t", "CE\t", "DF\t", "ES\t", "GO\t", "MA\t", "MT\t", "MS\t", "MG\t", "PA\t", "PB\t", "PR\t", "PE\t", "PI\t", "RN\t", "RS\t", "RO\t", "RR\t", "SC\t", "SP\t", "SE\t", "TO" }));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Nacionalidade");

        txtNacionalidade.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Endereço");

        txtEndereco.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Nº");

        txtNum.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("CEP");

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Bairro");

        txtBairro.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        try {
            txtCEP.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#####-###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtCEP.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Celular");

        try {
            txtCelular.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)#####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtCelular.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("E-mail");

        txtEmail.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailActionPerformed(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Cônjugue");

        txtConjugue.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(351, 351, 351)
                        .addComponent(jLabel18))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 372, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21)
                        .addComponent(txtConjugue, javax.swing.GroupLayout.PREFERRED_SIZE, 372, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(305, 305, 305)
                        .addComponent(jLabel5))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(txtNomePai, javax.swing.GroupLayout.PREFERRED_SIZE, 372, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21)
                        .addComponent(txtNomeMae, javax.swing.GroupLayout.PREFERRED_SIZE, 372, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1)
                        .addGap(357, 357, 357)
                        .addComponent(jLabel6)
                        .addGap(38, 38, 38)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addGap(71, 71, 71)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(112, 112, 112)
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(jLabel13))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(txtNacionalidade, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtNatural, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(cbxUF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(txtNum, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtBairro, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtCEP, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtCelular, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtCPF, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addGap(42, 42, 42)
                        .addComponent(jLabel16)
                        .addGap(235, 235, 235)
                        .addComponent(jLabel15)
                        .addGap(103, 103, 103)
                        .addComponent(jLabel17)
                        .addGap(111, 111, 111)
                        .addComponent(jLabel3))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(dateNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(cbxEstadoCivil, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(jLabel1)
                    .addComponent(jLabel6)
                    .addComponent(jLabel9))
                .addGap(6, 6, 6)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dateNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbxEstadoCivil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11)
                    .addComponent(jLabel13))
                .addGap(6, 6, 6)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtNacionalidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNatural, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbxUF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14)
                    .addComponent(jLabel16)
                    .addComponent(jLabel15)
                    .addComponent(jLabel17)
                    .addComponent(jLabel3))
                .addGap(6, 6, 6)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtBairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCEP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCelular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addGap(6, 6, 6)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtNomePai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNomeMae, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jLabel18))
                .addGap(6, 6, 6)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtConjugue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(92, Short.MAX_VALUE))
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {cbxEstadoCivil, cbxUF, dateNascimento, jLabel1, jLabel10, jLabel11, jLabel12, jLabel13, jLabel14, jLabel15, jLabel16, jLabel17, jLabel18, jLabel3, jLabel4, jLabel5, jLabel6, jLabel7, jLabel8, jLabel9, txtBairro, txtCEP, txtCPF, txtCelular, txtConjugue, txtEmail, txtEndereco, txtId, txtNacionalidade, txtNatural, txtNome, txtNomeMae, txtNomePai, txtNum});

        jTabbedPane1.addTab("Cadastrar Membro", jPanel2);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 51), 5));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 830, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 457, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Cadastro Eclesiástico", jPanel1);

        btnCadastrarMembro.setBackground(new java.awt.Color(0, 255, 204));
        btnCadastrarMembro.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnCadastrarMembro.setForeground(new java.awt.Color(255, 255, 255));
        btnCadastrarMembro.setText("<html><p sytle text_align:center;>CADASTRAR<br>MEMBRO</p></html>");
        btnCadastrarMembro.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCadastrarMembro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarMembroActionPerformed(evt);
            }
        });

        btnAlterarRegistro.setBackground(new java.awt.Color(0, 102, 153));
        btnAlterarRegistro.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnAlterarRegistro.setForeground(new java.awt.Color(255, 255, 255));
        btnAlterarRegistro.setText("<html><p sytle text_align:center;>ALTERAR<br>REGISTRO</p></html>");
        btnAlterarRegistro.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAlterarRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarRegistroActionPerformed(evt);
            }
        });

        btnCarregarCampos.setBackground(new java.awt.Color(204, 204, 0));
        btnCarregarCampos.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnCarregarCampos.setForeground(new java.awt.Color(255, 255, 255));
        btnCarregarCampos.setText("<html><p sytle text_align:center;>CARREGAR<br>CAMPOS</p></html>");
        btnCarregarCampos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCarregarCampos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCarregarCamposActionPerformed(evt);
            }
        });

        jScrollPane1.setWheelScrollingEnabled(false);

        tabelaMembro.setAutoCreateRowSorter(true);
        tabelaMembro.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        tabelaMembro.setForeground(new java.awt.Color(102, 102, 102));
        tabelaMembro.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "COD.", "NOME", "CPF", "NASCIMENTO", "CEP", "ENDEREÇO", "Nº", "BAIRRO", "CELULAR", "E-MAIL", "EST. CIVIL", "NACIONALIDADE", "NATURAL", "UF", "NOME DO PAI", "NOME DA MÃE", "CÔNJUGUE"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabelaMembro.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        tabelaMembro.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tabelaMembro);
        if (tabelaMembro.getColumnModel().getColumnCount() > 0) {
            tabelaMembro.getColumnModel().getColumn(0).setPreferredWidth(40);
            tabelaMembro.getColumnModel().getColumn(1).setPreferredWidth(150);
            tabelaMembro.getColumnModel().getColumn(2).setPreferredWidth(100);
            tabelaMembro.getColumnModel().getColumn(3).setPreferredWidth(70);
            tabelaMembro.getColumnModel().getColumn(4).setPreferredWidth(70);
            tabelaMembro.getColumnModel().getColumn(5).setPreferredWidth(150);
            tabelaMembro.getColumnModel().getColumn(6).setPreferredWidth(40);
            tabelaMembro.getColumnModel().getColumn(7).setPreferredWidth(150);
            tabelaMembro.getColumnModel().getColumn(8).setPreferredWidth(70);
            tabelaMembro.getColumnModel().getColumn(9).setPreferredWidth(150);
            tabelaMembro.getColumnModel().getColumn(10).setPreferredWidth(70);
            tabelaMembro.getColumnModel().getColumn(11).setPreferredWidth(70);
            tabelaMembro.getColumnModel().getColumn(12).setPreferredWidth(70);
            tabelaMembro.getColumnModel().getColumn(13).setPreferredWidth(30);
            tabelaMembro.getColumnModel().getColumn(14).setPreferredWidth(150);
            tabelaMembro.getColumnModel().getColumn(15).setPreferredWidth(150);
            tabelaMembro.getColumnModel().getColumn(16).setPreferredWidth(150);
        }

        jMenuBar2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jMenuBar2.setPreferredSize(new java.awt.Dimension(70, 30));

        jMenu3.setText("File");
        jMenuBar2.add(jMenu3);

        jMenu4.setText("Edit");
        jMenuBar2.add(jMenu4);

        setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 840, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnCadastrarMembro, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnAlterarRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnExcluirMembro, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnCarregarCampos, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(28, 28, 28))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(btnCadastrarMembro, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnAlterarRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnExcluirMembro, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnCarregarCampos, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnExcluirMembroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirMembroActionPerformed

        try {
            ExcluirMembro();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(FrmCadastrarMembroVIEW.class.getName()).log(Level.SEVERE, null, ex);
        }
        LimparCampos();
        ListarMembros();

    }//GEN-LAST:event_btnExcluirMembroActionPerformed

    private void txtNomePaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomePaiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomePaiActionPerformed

    private void txtEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailActionPerformed

    private void btnCadastrarMembroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarMembroActionPerformed

        try {
            CadastrarMembro();
        } catch (ClassNotFoundException | ParseException ex) {
            Logger.getLogger(FrmCadastrarMembroVIEW.class.getName()).log(Level.SEVERE, null, ex);
        }
        LimparCampos();
        ListarMembros();

    }//GEN-LAST:event_btnCadastrarMembroActionPerformed

    private void btnAlterarRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarRegistroActionPerformed
        
        try {
            AlterarMembro();
        } catch (ClassNotFoundException | ParseException ex) {
            Logger.getLogger(FrmCadastrarMembroVIEW.class.getName()).log(Level.SEVERE, null, ex);
        }
        LimparCampos();
        ListarMembros();
        
    }//GEN-LAST:event_btnAlterarRegistroActionPerformed

    private void btnCarregarCamposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCarregarCamposActionPerformed

        carregarCampos();

    }//GEN-LAST:event_btnCarregarCamposActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("FlatLaf Dark".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmCadastrarMembroVIEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmCadastrarMembroVIEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmCadastrarMembroVIEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmCadastrarMembroVIEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new FrmCadastrarMembroVIEW().setVisible(true);
                } catch (ParseException ex) {
                    Logger.getLogger(FrmCadastrarMembroVIEW.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlterarRegistro;
    private javax.swing.JButton btnCadastrarMembro;
    private javax.swing.JButton btnCarregarCampos;
    private javax.swing.JButton btnExcluirMembro;
    private javax.swing.JComboBox<String> cbxEstadoCivil;
    private javax.swing.JComboBox<String> cbxUF;
    private datechooser.beans.DateChooserDialog dateChooserDialog1;
    private datechooser.beans.DateChooserDialog dateChooserDialog2;
    private datechooser.beans.DateChooserDialog dateChooserDialog3;
    private datechooser.beans.DateChooserDialog dateChooserDialog4;
    private datechooser.beans.DateChooserCombo dateNascimento;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable tabelaMembro;
    private javax.swing.JTextField txtBairro;
    private javax.swing.JFormattedTextField txtCEP;
    private javax.swing.JFormattedTextField txtCPF;
    private javax.swing.JFormattedTextField txtCelular;
    private javax.swing.JTextField txtConjugue;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtEndereco;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtNacionalidade;
    private javax.swing.JTextField txtNatural;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtNomeMae;
    private javax.swing.JTextField txtNomePai;
    private javax.swing.JTextField txtNum;
    // End of variables declaration//GEN-END:variables

    private void CadastrarMembro() throws ClassNotFoundException, ParseException {

        String cpf_membro, nome_membro, pai_membro, mae_membro, nascimento_membro, idade_membro, numeroEnd_membro, estadoCivil_membro, nacionalidade_membro, natural_membro, uf_membro, endereco_membro, bairro_membro, cep_membro, celular_membro, email_membro, conjugue_membro;
        SimpleDateFormat formatador = new SimpleDateFormat("yyyy-dd-MM");

        LocalDate ano_atual = LocalDate.now();
        LocalDate ano_nascimento = dateNascimento.getSelectedDate().getTime().toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
        Period periodo = Period.between(ano_nascimento, ano_atual);
        idade_membro = String.valueOf(periodo.getYears());

        cpf_membro = txtCPF.getText();
        nome_membro = txtNome.getText();
        pai_membro = txtNomePai.getText();
        mae_membro = txtNomeMae.getText();
        nascimento_membro = formatador.format(new Date(dateNascimento.getText()));
        estadoCivil_membro = cbxEstadoCivil.getSelectedItem().toString();
        nacionalidade_membro = txtNacionalidade.getText();
        natural_membro = txtNatural.getText();
        uf_membro = cbxUF.getSelectedItem().toString();
        endereco_membro = txtEndereco.getText();
        numeroEnd_membro = txtNum.getText();
        bairro_membro = txtBairro.getText();
        cep_membro = txtCEP.getText();
        celular_membro = txtCelular.getText();
        email_membro = txtEmail.getText();
        conjugue_membro = txtConjugue.getText();

        MembroDTO objMembroDTO = new MembroDTO();
        objMembroDTO.setCpf_membro(cpf_membro);
        objMembroDTO.setNome_membro(nome_membro);
        objMembroDTO.setPai_membro(pai_membro);
        objMembroDTO.setMae_membro(mae_membro);
        objMembroDTO.setNascimento_membro(nascimento_membro);
        objMembroDTO.setIdade_membro(idade_membro);
        objMembroDTO.setEstadoCivil_membro(estadoCivil_membro);
        objMembroDTO.setNacionalidade_membro(nacionalidade_membro);
        objMembroDTO.setNatural_membro(natural_membro);
        objMembroDTO.setUf_membro(uf_membro);
        objMembroDTO.setEndereco_membro(endereco_membro);
        objMembroDTO.setNumeroEnd_membro(numeroEnd_membro);
        objMembroDTO.setBairro_membro(bairro_membro);
        objMembroDTO.setCep_membro(cep_membro);
        objMembroDTO.setCelular_membro(celular_membro);
        objMembroDTO.setEmail_membro(email_membro);
        objMembroDTO.setConjugue_membro(conjugue_membro);

        MembroDAO objMembroDAO = new MembroDAO();
        objMembroDAO.cadastrarMembro(objMembroDTO);
        
        
        txtNome.requestFocus();
    }
    
    private void AlterarMembro() throws ClassNotFoundException, ParseException {

        int id_membro;
        String cpf_membro, nome_membro, pai_membro, mae_membro, nascimento_membro, idade_membro, numeroEnd_membro, estadoCivil_membro, nacionalidade_membro, natural_membro, uf_membro, endereco_membro, bairro_membro, cep_membro, celular_membro, email_membro, conjugue_membro;
        SimpleDateFormat formatador = new SimpleDateFormat("yyyy-dd-MM");

        LocalDate ano_atual = LocalDate.now();
        LocalDate ano_nascimento = dateNascimento.getSelectedDate().getTime().toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
        Period periodo = Period.between(ano_nascimento, ano_atual);
        idade_membro = String.valueOf(periodo.getYears());

        id_membro = Integer.parseInt(txtId.getText());
        cpf_membro = txtCPF.getText();
        nome_membro = txtNome.getText();
        pai_membro = txtNomePai.getText();
        mae_membro = txtNomeMae.getText();
        nascimento_membro = formatador.format(new Date(dateNascimento.getText()));
        estadoCivil_membro = cbxEstadoCivil.getSelectedItem().toString();
        nacionalidade_membro = txtNacionalidade.getText();
        natural_membro = txtNatural.getText();
        uf_membro = cbxUF.getSelectedItem().toString();
        endereco_membro = txtEndereco.getText();
        numeroEnd_membro = txtNum.getText();
        bairro_membro = txtBairro.getText();
        cep_membro = txtCEP.getText();
        celular_membro = txtCelular.getText();
        email_membro = txtEmail.getText();
        conjugue_membro = txtConjugue.getText();

        MembroDTO objMembroDTO = new MembroDTO();
        objMembroDTO.setId_membro(id_membro);
        objMembroDTO.setCpf_membro(cpf_membro);
        objMembroDTO.setNome_membro(nome_membro);
        objMembroDTO.setPai_membro(pai_membro);
        objMembroDTO.setMae_membro(mae_membro);
        objMembroDTO.setNascimento_membro(nascimento_membro);
        objMembroDTO.setIdade_membro(idade_membro);
        objMembroDTO.setEstadoCivil_membro(estadoCivil_membro);
        objMembroDTO.setNacionalidade_membro(nacionalidade_membro);
        objMembroDTO.setNatural_membro(natural_membro);
        objMembroDTO.setUf_membro(uf_membro);
        objMembroDTO.setEndereco_membro(endereco_membro);
        objMembroDTO.setNumeroEnd_membro(numeroEnd_membro);
        objMembroDTO.setBairro_membro(bairro_membro);
        objMembroDTO.setCep_membro(cep_membro);
        objMembroDTO.setCelular_membro(celular_membro);
        objMembroDTO.setEmail_membro(email_membro);
        objMembroDTO.setConjugue_membro(conjugue_membro);

        MembroDAO objMembroDAO = new MembroDAO();
        objMembroDAO.AlterarMembro(objMembroDTO);
        
        
        txtNome.requestFocus();
    }

    private void ListarMembros() {

        try {
            MembroDAO objMembroDAO = new MembroDAO();
            DefaultTableModel model = (DefaultTableModel) tabelaMembro.getModel();
            model.setNumRows(0);

            ArrayList<MembroDTO> lista_membro = objMembroDAO.pesquisarMembro();

            for (int num = 0; num < lista_membro.size(); num++) {
                model.addRow(new Object[]{
                    lista_membro.get(num).getId_membro(),
                    lista_membro.get(num).getNome_membro(),
                    lista_membro.get(num).getCpf_membro(),
                    lista_membro.get(num).getNascimento_membro(),
                    lista_membro.get(num).getCep_membro(),
                    lista_membro.get(num).getEndereco_membro(),
                    lista_membro.get(num).getNumeroEnd_membro(),
                    lista_membro.get(num).getBairro_membro(),
                    lista_membro.get(num).getCelular_membro(),
                    lista_membro.get(num).getEmail_membro(),
                    lista_membro.get(num).getEstadoCivil_membro(),
                    lista_membro.get(num).getNacionalidade_membro(),
                    lista_membro.get(num).getNatural_membro(),
                    lista_membro.get(num).getUf_membro(),
                    lista_membro.get(num).getPai_membro(),
                    lista_membro.get(num).getMae_membro(),
                    lista_membro.get(num).getConjugue_membro(),});

            }
        } catch (ClassNotFoundException e) {
            JOptionPane.showMessageDialog(null, "Erro ao Exibir Lista de Membros " + e);

        }
    }

    private void carregarCampos() {
        int setar = tabelaMembro.getSelectedRow();

        txtId.setText(tabelaMembro.getModel().getValueAt(setar, 0).toString());
        txtNome.setText(tabelaMembro.getModel().getValueAt(setar, 1).toString());
        txtCPF.setText(tabelaMembro.getModel().getValueAt(setar, 2).toString());
        dateNascimento.setText(tabelaMembro.getModel().getValueAt(setar, 3).toString());
        txtCEP.setText(tabelaMembro.getModel().getValueAt(setar, 4).toString());
        txtEndereco.setText(tabelaMembro.getModel().getValueAt(setar, 5).toString());
        txtNum.setText(tabelaMembro.getModel().getValueAt(setar, 6).toString());
        txtBairro.setText(tabelaMembro.getModel().getValueAt(setar, 7).toString());
        txtCelular.setText(tabelaMembro.getModel().getValueAt(setar, 8).toString());
        txtEmail.setText(tabelaMembro.getModel().getValueAt(setar, 9).toString());
        cbxEstadoCivil.setSelectedItem(tabelaMembro.getModel().getValueAt(setar, 10).toString());
        txtNacionalidade.setText(tabelaMembro.getModel().getValueAt(setar, 11).toString());
        txtNatural.setText(tabelaMembro.getModel().getValueAt(setar, 12).toString());
        cbxUF.setSelectedItem(tabelaMembro.getModel().getValueAt(setar, 13).toString());
        txtNomePai.setText(tabelaMembro.getModel().getValueAt(setar, 14).toString());
        txtNomeMae.setText(tabelaMembro.getModel().getValueAt(setar, 15).toString());
        txtConjugue.setText(tabelaMembro.getModel().getValueAt(setar, 16).toString());
        txtNome.requestFocus();
    }

    private void ExcluirMembro() throws ClassNotFoundException {
        int id_membro;

        id_membro = Integer.parseInt(txtId.getText());

        MembroDTO objMembroDTO = new MembroDTO();
        objMembroDTO.setId_membro(id_membro);

        MembroDAO objMembroDAO = new MembroDAO();
        objMembroDAO.ExcluirMembro(objMembroDTO);

    }

    private void LimparCampos() {

        txtId.setText("");
        txtNome.setText("");
        dateNascimento.setText("");
        cbxEstadoCivil.setSelectedIndex(0);
        txtNacionalidade.setText("");
        txtNatural.setText("");
        cbxUF.setSelectedIndex(0);
        txtEndereco.setText("");
        txtNum.setText("");
        txtBairro.setText("");
        txtCEP.setText("");
        txtCelular.setText("");
        txtCPF.setText("");
        txtNomePai.setText("");
        txtNomeMae.setText("");
        txtEmail.setText("");
        txtConjugue.setText("");
        txtNome.requestFocus();
    }

}
