/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.br.VIEW;

import com.br.DAO.MembroDAO;
import com.br.DTO.MembroDTO;
import java.awt.Color;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author lukas
 */
public class FrmListaDeMembros extends javax.swing.JFrame {

    /**
     * Creates new form FrmListaDeMembros
     */
    public FrmListaDeMembros() {
        getContentPane().setBackground(Color.black);
        initComponents();
        ListarMembros();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaMembro = new javax.swing.JTable();
        btnExcluirMembro = new javax.swing.JButton();
        btnTelaPrincipal = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 204));
        jPanel1.setPreferredSize(new java.awt.Dimension(800, 30));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        tabelaMembro.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        tabelaMembro.setForeground(new java.awt.Color(102, 102, 102));
        tabelaMembro.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "COD.", "NOME", "SOBRENOME", "CPF", "NASCIMENTO", "BATISMO"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabelaMembro.setSelectionForeground(new java.awt.Color(255, 255, 255));
        tabelaMembro.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tabelaMembro);
        if (tabelaMembro.getColumnModel().getColumnCount() > 0) {
            tabelaMembro.getColumnModel().getColumn(0).setResizable(false);
            tabelaMembro.getColumnModel().getColumn(0).setPreferredWidth(20);
            tabelaMembro.getColumnModel().getColumn(1).setResizable(false);
            tabelaMembro.getColumnModel().getColumn(1).setPreferredWidth(60);
            tabelaMembro.getColumnModel().getColumn(2).setResizable(false);
            tabelaMembro.getColumnModel().getColumn(2).setPreferredWidth(160);
            tabelaMembro.getColumnModel().getColumn(3).setResizable(false);
            tabelaMembro.getColumnModel().getColumn(3).setPreferredWidth(80);
            tabelaMembro.getColumnModel().getColumn(4).setResizable(false);
            tabelaMembro.getColumnModel().getColumn(4).setPreferredWidth(80);
            tabelaMembro.getColumnModel().getColumn(5).setResizable(false);
            tabelaMembro.getColumnModel().getColumn(5).setPreferredWidth(80);
        }

        btnExcluirMembro.setBackground(new java.awt.Color(0, 0, 255));
        btnExcluirMembro.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnExcluirMembro.setForeground(new java.awt.Color(255, 255, 255));
        btnExcluirMembro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/ExcluirMembro.png"))); // NOI18N
        btnExcluirMembro.setText("<html>EXCLUIR<br> MEMBRO</html>");
        btnExcluirMembro.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnExcluirMembro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirMembroActionPerformed(evt);
            }
        });

        btnTelaPrincipal.setBackground(new java.awt.Color(153, 255, 255));
        btnTelaPrincipal.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnTelaPrincipal.setForeground(new java.awt.Color(51, 51, 51));
        btnTelaPrincipal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/TelaPrincipal.png"))); // NOI18N
        btnTelaPrincipal.setText("<html>TELA<br> PRINCIPAL</html>");
        btnTelaPrincipal.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnTelaPrincipal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTelaPrincipalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 760, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(134, 134, 134)
                .addComponent(btnTelaPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnExcluirMembro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(123, 123, 123))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnExcluirMembro, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTelaPrincipal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnExcluirMembroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirMembroActionPerformed

        try {
            ExcluirMembro();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(FrmListaDeMembros.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        ListarMembros();

    }//GEN-LAST:event_btnExcluirMembroActionPerformed

    private void btnTelaPrincipalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTelaPrincipalActionPerformed

        FrmPrincipalVIEW objFrmPrincipalVIEW = new FrmPrincipalVIEW();
        objFrmPrincipalVIEW.setVisible(true);
        dispose();

    }//GEN-LAST:event_btnTelaPrincipalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmListaDeMembros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmListaDeMembros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmListaDeMembros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmListaDeMembros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmListaDeMembros().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExcluirMembro;
    private javax.swing.JButton btnTelaPrincipal;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabelaMembro;
    // End of variables declaration//GEN-END:variables

    private void ListarMembros() {

        try {
            MembroDAO objMembroDAO = new MembroDAO();
            DefaultTableModel model = (DefaultTableModel) tabelaMembro.getModel();
            model.setNumRows(0);

            ArrayList<MembroDTO> lista_membro = objMembroDAO.pesquisarMembro();

            for (int num = 0; num < lista_membro.size(); num++) {
                model.addRow(new Object[]{
                    lista_membro.get(num).getId_membro(),
                    lista_membro.get(num).getNome_membro(),
                    lista_membro.get(num).getSobrenome_membro(),
                    lista_membro.get(num).getCpf_membro(),
                    lista_membro.get(num).getNascimento_membro(),
                    lista_membro.get(num).getBatismo_membro()
                });

            }
        } catch (ClassNotFoundException e) {
            JOptionPane.showMessageDialog(null, "Erro ao Exibir Lista de Membros " + e);

        }
    }
    
    private void ExcluirMembro() throws ClassNotFoundException{
        MembroDTO objMembroDTO = new MembroDTO();
        MembroDAO objMembroDAO = new MembroDAO();
        
        objMembroDTO.setId_membro((int) tabelaMembro.getValueAt(tabelaMembro.getSelectedRow(), 0));
        objMembroDAO.ExcluirMembro(objMembroDTO);
        
    }
}
